<?php

/**
 * MainCategory
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    atuo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MainCategory extends BaseMainCategory
{
    /**
     * Returns all entity types contained within the category.
     *
     * @return arrray
     */
    public function getEntityTypes()
    {
        $connection = Doctrine_Manager::connection();
        /* @var PDOStatement $results */
        $results = $connection->execute('
        	SELECT DISTINCT(type)
        	FROM entity e
        	INNER JOIN main_category_entity me
        		ON e.id = me.entity_id
        		AND me.main_category_id = ?', array($this->id));
        $entityTypes = array_keys($results->fetchAll(PDO::FETCH_UNIQUE));

        return $entityTypes;
    }
}
