Entity:
  actAs:
    Timestampable: ~
    Sluggable: ~
    I18n:
      fields: [title, body]
  columns:
    author:     string
    is_enabled:
      type: boolean
      default: false

MainCategory:
  inheritance:
    extends: Entity
    type: column_aggregation
    keyField: type
    keyValue: 2

Page:
  inheritance:
    extends: Entity
    type: column_aggregation
    keyField: type
    keyValue: 3

# TODO : implement "Sellable" behavior (is_in_stock, price, etc)
Item:
  inheritance:
    extends: Entity
    type: column_aggregation
    keyField: type
    keyValue: 4
  columns:
    title:          string
    body:           string
    image_original: string
    image_thumb:    string

Poster:
  inheritance:
    extends: Item
    type: column_aggregation
    keyField: type
    keyValue: 5

Book:
  inheritance:
    extends: Item
    type: column_aggregation
    keyField: type
    keyValue: 6
    
Gear:
  inheritance:
    extends: Item
    type: column_aggregation
    keyField: type
    keyValue: 7
    
GraphicDesign:
  inheritance:
    extends: Item
    type: column_aggregation
    keyField: type
    keyValue: 8
    
ArtPrint:
  inheritance:
    extends: Item
    type: column_aggregation
    keyField: type
    keyValue: 9
    
Record:
  inheritance:
    extends: Item
    type: column_aggregation
    keyField: type
    keyValue: 10
    
Logo:
  inheritance:
    extends: Item
    type: column_aggregation
    keyField: type
    keyValue: 11
    
Card:
  inheritance:
    extends: Item
    type: column_aggregation
    keyField: type
    keyValue: 12

Other:
  inheritance:
    extends: Item
    type: column_aggregation
    keyField: type
    keyValue: 13
    
Event:
  inheritance:
    extends: Item
    type: column_aggregation
    keyField: type
    keyValue: 20
  columns:
    starts_on: date

Concert:
  inheritance:
    extends: Event
    type: column_aggregation
    keyField: type
    keyValue: 21

Exhibition:
  inheritance:
    extends: Event
    type: column_aggregation
    keyField: type
    keyValue: 22