Entity:
  actAs:
    Timestampable: ~
    Sluggable: ~
    I18n:
      fields: [title, body]
  columns:
    id:
      type:          integer(4)
      autoincrement: true
      primary:       true
    author: string
    title: string
    type_slug: string
    is_enabled:
      type: boolean
      default: false

MainCategory:
  actAs:
    Timestampable: ~
    Sluggable: ~
    I18n:
      fields: [title, body]
  columns:
    id:
      type:          integer(4)
      autoincrement: true
      primary:       true
    author: string
    title: string
    is_enabled:
      type:    boolean
      default: false
  relations:
    Entities:
      foreignAlias: MainCategories
      class:        Entity
      refClass:     MainCategoryEntity

MainCategoryEntity:
  columns:
    main_category_id:
      type:          integer(4)
      primary:       true
    entity_id:
      type:          integer(4)
      primary:       true

MainCategoryEntityTypeSettings:
  columns:
    type: string
    sort_attribute: string
    view_name: string

Page:
  inheritance:
    extends:  Entity
    type:     column_aggregation
    keyField: type
    keyValue: Page

# TODO : implement "Sellable" behavior (is_in_stock, price, etc)
Item:
  inheritance:
    extends:  Entity
    type:     column_aggregation
    keyField: type
    keyValue: Item
  columns:
    title:          string
    body:           string
    image_original: string
    image_thumb:    string

Poster:
  inheritance:
    extends:  Item
    type:     column_aggregation
    keyField: type
    keyValue: Poster
  columns:
    year: string

Flyer:
  inheritance:
    extends:  Item
    type:     column_aggregation
    keyField: type
    keyValue: Flyer
  columns:
    year: string

Book:
  inheritance:
    extends:  Item
    type:     column_aggregation
    keyField: type
    keyValue: Book
    
Gear:
  inheritance:
    extends:  Item
    type:     column_aggregation
    keyField: type
    keyValue: Gear
    
GraphicDesign:
  inheritance:
    extends:  Item
    type:     column_aggregation
    keyField: type
    keyValue: GraphicDesign
  columns:
    subcategory: 
      type: enum
      values: [Illustration, Graphisme]
    
ArtPrint:
  inheritance:
    extends:  Item
    type:     column_aggregation
    keyField: type
    keyValue: ArtPrint
    
Record:
  inheritance:
    extends:  Item
    type:     column_aggregation
    keyField: type
    keyValue: Record
    
Logo:
  inheritance:
    extends:  Item
    type:     column_aggregation
    keyField: type
    keyValue: Logo
    
Card:
  inheritance:
    extends:  Item
    type:     column_aggregation
    keyField: type
    keyValue: Card

Other:
  inheritance:
    extends:  Item
    type:     column_aggregation
    keyField: type
    keyValue: Other
    
Event:
  inheritance:
    extends:  Item
    type:     column_aggregation
    keyField: type
    keyValue: Event
  columns:
    starts_on: date

Concert:
  inheritance:
    extends:  Event
    type:     column_aggregation
    keyField: type
    keyValue: Concert

Exhibition:
  inheritance:
    extends:  Event
    type:     column_aggregation
    keyField: type
    keyValue: Exhibition